# Generated by Django 3.1.5 on 2021-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_auto_20210304_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
