# Generated by Django 3.1.5 on 2021-03-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_auto_20210304_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.TextField(default='', help_text='내용을 입력해주세요~'),
        ),
    ]
