# Generated by Django 3.1.5 on 2021-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('upw', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(help_text='"-" 제외하고 입력해주세요.', max_length=11)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
