# Generated by Django 3.1.5 on 2021-03-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myalbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.CharField(max_length=50)),
                ('a_title', models.CharField(max_length=255)),
                ('a_note', models.CharField(max_length=4096)),
                ('a_image', models.CharField(max_length=1000)),
                ('a_count', models.IntegerField(default=0)),
                ('a_datetime', models.DateTimeField()),
                ('a_usage', models.CharField(max_length=10)),
            ],
        ),
    ]
