# Generated by Django 3.1.5 on 2021-03-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('a_no', models.AutoField(primary_key=True, serialize=False)),
                ('a_type', models.CharField(max_length=50)),
                ('a_title', models.CharField(max_length=255)),
                ('a_note', models.CharField(max_length=4096)),
                ('a_image', models.CharField(max_length=1000)),
                ('a_count', models.IntegerField(default=0)),
                ('a_datetime', models.DateTimeField(auto_now=True)),
                ('a_usage', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
    ]
