# Generated by Django 3.1.5 on 2021-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
